apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-web-ec2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-web-ec2
  template:
    metadata:
      labels:
        app: python-web-ec2
    spec:
      containers:
      - name: python-web-ec2
        image: tnobe/python-web-ec2
        ports:
        - containerPort: 8000
